### ISSUE TITLE
would `{generate(),view()}.with_*` for styling, etc be possible?

### ISSUE THREAD

**Issue by 1sra3l** [MoAlyousef/fltk-form#6]
Or is there a way to quickly theme all elements inside a Group that would make this redundant?
Is this type of thing accessible using `*_prop_()`?
Thanks again for doing this!

**Comment by MoAlyousef** [comment]
Currently you could do it, but that would require unsafe. (It’s basically the same mechanism for props, casting to a group and iterating over the children). A wrapper could be written in the library to make things safe. Unfortunately these coming days I’m kinda busy with a few things. Hopefully next weekend I’ll have more time.

**Comment by MoAlyousef** [comment]
I have added a .get_widget() method which takes a prop:
```rust
    let mut c = form.get_widget("c").unwrap();
    c.set_color(Color::Red.inactive());
```

**Comment by 1sra3l** [comment]
Wow, that is even more than I needed.  I am going to experiment with all this feature has to offer!  Much more than just styling!
I do intend to try to make an example at some point that is both simple and complicated enough to show enough clearly, so I am sure `get_widget()` will be really useful.
